### ISSUE TITLE
Missing of the "Submit" button in the entry form for adding emails

### ISSUE THREAD

**Issue by tawahle** [Symplectic/Bootstrapped-VIVO#2]
Hi!
I miss the "Submit" button in the entry form "Create email address for".  

![image](https://cloud.githubusercontent.com/assets/6906832/22245036/3aa4bf36-e22e-11e6-8c8b-515d869d3929.png)

Regards,
Tatiana W.

**Comment by ghost** [comment]
Hi Tatiana,

Thanks so much for pointing out this bug. These will appear from time to time as the theme is still in beta. I can confirm that I have pushed a fix, please feel free to reapply the theme with the latest files, and you should see the Create button reappear.

https://github.com/Symplectic/Bootstrapped-VIVO/commit/fc996dea18adf1e8e0dfa1ca9b6fb417c457a676

Cheers,
Sabih
