### ISSUE TITLE
3rd Party JQuery Library

### ISSUE THREAD

**Issue by 12344545rgferts** [Symplectic/Bootstrapped-VIVO#3]
We figured out that the file headScripts.ftl uses a 3rd Party (Google) JQuery Library. We’d like to change that for privacy reasons. Please update the headScripts.ftl and include the  JQuery Library into the Bootstrapped theme.

**Comment by johnfearns22-symplectic-admin** [comment]
This repository is being archived. As such, all open issues are being closed.
