### ISSUE TITLE
JQuery Library not compatible with VIVO JQuery Library

### ISSUE THREAD

**Issue by 12344545rgferts** [Symplectic/Bootstrapped-VIVO#4]
The headScripts.ftl makes use of an outdated JQuery Library, which is not compatible with the JQuery Library already included in the VIVO project. We strongly suggest to only use the version used by VIVO instead commenting it out, like it’s done right now.
See headScripts.ftl line seven and eight.

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
Please note that the dropdown menu (“Browse”) does not work anymore when updating the JQuery Library. Maybe a CSS solution would be sufficient here?

**Comment by johnfearns22-symplectic-admin** [comment]
This repository is being archived. As such, all open issues are being closed.
